// <auto-generated />
using System;
using Asp.net_core_api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asp.net_core_api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspcoreApi.share.passengers", b =>
                {
                    b.Property<int>("Pass_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pass_ID"));

                    b.Property<int?>("Pass_Balance")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Pass_BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("Pass_Flags")
                        .HasColumnType("smallint");

                    b.Property<string>("Pass_FristName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Pass_GenderM")
                        .HasColumnType("int");

                    b.Property<string>("Pass_LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass_Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Pass_PhoneNumber")
                        .HasColumnType("bigint");

                    b.Property<short?>("Pass_Rank")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Pass_Rating")
                        .HasColumnType("tinyint");

                    b.Property<string>("Pass_SecondName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Pass_Status")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Pass_languge")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("email_verified_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Pass_ID");

                    b.ToTable("passengers");
                });
#pragma warning restore 612, 618
        }
    }
}
